FROM elasticsearch:6.8.6

LABEL maintainer="shiguanghuxian <shiguanghuxian@live.com>"

RUN ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.8.6/elasticsearch-analysis-ik-6.8.6.zip
